name: Architecture Validation

on:
  push:
    branches: [main, master, develop]
  pull_request:
    branches: [main, master, develop]

jobs:
  validate-architecture:
    name: Validate Clean Architecture
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Validate architecture boundaries
        run: npm run check-arch
      
      - name: Run ESLint checks
        run: npm run lint
      
      - name: Run integration tests
        run: npm test -- --testPathPattern=src/__tests__/integration
      
      - name: Visualize dependency graph (on failure)
        if: failure()
        run: npm run visualize-deps
      
      - name: Upload dependency graph (on failure)
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: dependency-graph
          path: dependency-graph.svg
          
  architecture-report:
    name: Generate Architecture Report
    runs-on: ubuntu-latest
    needs: validate-architecture
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Generate architecture report
        run: |
          mkdir -p architecture-report
          npx depcruise --include-only "^src" --output-type dot src | dot -T svg > architecture-report/dependency-graph.svg
          echo "# Architecture Validation Report" > architecture-report/report.md
          echo "## Generated on $(date)" >> architecture-report/report.md
          echo "## Dependency Graph" >> architecture-report/report.md
          echo "![Dependency Graph](dependency-graph.svg)" >> architecture-report/report.md
          echo "## Architecture Compliance" >> architecture-report/report.md
          npm run validate-arch >> architecture-report/report.md 2>&1 || true
      
      - name: Upload architecture report
        uses: actions/upload-artifact@v3
        with:
          name: architecture-report
          path: architecture-report
